ALTER TABLE containers
  ADD COLUMN IF NOT EXISTS qr_code TEXT UNIQUE,
  ADD COLUMN IF NOT EXISTS qr_assigned_at TIMESTAMP WITH TIME ZONE;

ALTER TABLE items
  ADD COLUMN IF NOT EXISTS qr_code TEXT UNIQUE,
  ADD COLUMN IF NOT EXISTS qr_assigned_at TIMESTAMP WITH TIME ZONE;
